//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type MatchCategory struct {
	ID      int32 `sql:"primary_key"`
	L1      string
	L2      *string
	L3      *string
	L4      *string
	L5      *string
	L6      *string
	L7      *string
	L8      *string
	MatchID *int32
}
